### PR TITLE
E0d/merge stanford

### PR DESCRIPTION
**Pull request by e0d**
Branch to pull in the Stanford fork's changes

@caesar2164 @stvstnfrd @nedbat

### CODE REVIEW

**Comment by stvstnfrd** [comment]
This is great to see! Thanks @e0d!

I'm on vacation this week, but can follow up more next week.

CC: @caseylitton

**Comment by e0d** [comment]
@stvstnfrd ping.  @nedbat are you OK with this?

**Comment by stvstnfrd** [comment]
@e0d We're good with this, but I should note a few caveats:

Our version not only deprecates but actually drops support for the old renderers.
Only the new, fully YAML-based configuration renderer (aka `v4`) is now supported.
Operators of existing installations would need to migrate to the new renderer;
old templates would no longer work.

We also have a few small changes to the `certificates` role in our configuration repo/fork.
I don't think any of those changes are tied to these code changes here,
but we probably should circle back to sync the two up (our role vs yours).

**Comment by nedbat** [comment]
@e0d I wouldn't know how to evaluate this.  I can try to get other users of the code from the community to chime in if that would help?

**Comment by e0d** [comment]
@nedbat that would be helpful

**Comment by bradenmacdonald** [comment]
@stvstnfrd @caesar2164 Could you please summarize what changes this PR makes? Does this only affect PDF certificates, or is there an impact for HTML certs too?

**Comment by caesar2164** [comment]
@bradenmacdonald - this only affects PDF certificates, and makes it so that the certificates can be completely generated through YAML alone without any base template. This also allows for complete customization of the template and the applied text (as well as translation of that text) through the YAML.

The best way to get an idea of the functionality is to look through the `cert-data.yml` file, that file gives extensive documentation on what things do.

**Comment by crice100** [comment]
Closing since this PR hasn't been updated in a while. Feel free to re-open if it is still needed.

**Pull request closed without merging**
