### PR TITLE
E0d/requiremnents and improvements

### PR DESCRIPTION
**Pull request by e0d**
WIP 
* upgrade requirements
* add gpg key passphrase support and helper files for key generation
* add better docs around gpg key usage
* use requests everywhere
* use moto and mock_s3 for tests

### CODE REVIEW

**Comment by e0d** [comment]
@stvstnfrd @caesar2164 Can one of y'all review?  Started out upgrading all the requirements, but added some doc and refactored this and that along the way.

**Comment by e0d** [comment]
@edx/devops we own this and some of the requirements were out of date.  Would love a review.

**Comment by caesar2164** [comment]
Honestly, @e0d, you guys may actually want to just switch to using our fork.

We've made HUGE improvements to the certificates repo: https://github.com/Stanford-Online/openedx-certificates
- remove all but one renderer
- everything is done through the cert-data.yml file (lots of documentation in the default one)
- all text is translatable
- templates are generated in YAML and reused
- etc...

**Comment by e0d** [comment]
If you're not using this repo at all, I won't worry about breaking you.  It might be nice to merge your changes back here, but I have no idea how tractable that would be.  We are not using this at all ourselves, but I'm still committed to update the requirements at least.  Open to other directions too, but as a second order thing.

**Comment by caesar2164** [comment]
@e0d, since you guys don't use the repo and we do use ours, wouldn't it just be better to sunset this one and you guys reference our repo?

We'd be glad to take PRs to improve ours...

**Comment by caesar2164** [comment]
btw, the merge base between our two masters is 48f9b3538d09a9a2e5c43a9d5a825711c06d1014, so 6 commits from your HEAD and 102 from our HEAD.

**Comment by e0d** [comment]
@caesar2164 resolving the conflicts looks easy enough.  How do you feel about going to boto3 and using moto to mock s3 in tests?

**Comment by caesar2164** [comment]
@e0d that's probably fine, but I'd want @stvstnfrd to weigh in as well.

**Comment by crice100** [comment]
Closing since this PR hasn't been updated in a while. Feel free to re-open if it is still needed.

**Pull request closed without merging**
