### PR TITLE
WIP: Refactor certificate agent and queue

### PR DESCRIPTION
**Pull request by stvstnfrd**
Details to follow...

### CODE REVIEW

**Comment by sarina** [comment]
Happy 2015 @stvstnfrd ! Anything I can do to help with htis PR?

**Comment by stvstnfrd** [comment]
Happy 2015 to you too, @sarina! Thanks for following up...

I've got to page this back in, as we (Stanford) have been off throughout
the holidays. Though from what I remember, all that remained was
cleaning up tests and (maybe?) extending code coverage a bit.

I'll be going through this today and will ping you once it's ready for a
final review.

**Comment by sarina** [comment]
@stvstnfrd : ping

**Comment by sarina** [comment]
@stvstnfrd : are you still working on this? If not, or you don't have bandwidth at the current time, perhaps we can close this and open a new PR when it's ready for work and attention.

**Comment by stvstnfrd** [comment]
Hey @sarina . Thanks for following up. Yeah, I haven't had a chance to revisit this. Given recent shifts here on our team, I don't see it happening soon :(

Hopefully I can sneak this in on some weekend while I'm _not_ PEP8/Pylinting the platform :)

**Comment by sarina** [comment]
@stvstnfrd do you mind if I close it? It's a lot of overhead for me to do my twice monthly checks to make sure we're not losing PRs to have to keep kicking old PRs.

**Comment by stvstnfrd** [comment]
Voila.

**Comment by stvstnfrd** [comment]
Will revisit in the future, time permitting.

**Pull request closed without merging**
